-- MySQL Script generated by MySQL Workbench
-- Thu Jun  9 12:12:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RookiesCMS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RookiesCMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RookiesCMS` DEFAULT CHARACTER SET utf8 ;
USE `RookiesCMS` ;

-- -----------------------------------------------------
-- Table `RookiesCMS`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image_link` VARCHAR(255) NOT NULL,
  `image_alt` VARCHAR(100) NOT NULL,
  `status` TINYINT NOT NULL,
  `url` VARCHAR(255) NULL,
  `categorie` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idimages_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `languages` VARCHAR(2) NOT NULL,
  `images_id` INT NOT NULL,
  PRIMARY KEY (`id`, `images_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_languages_images1_idx` (`images_id` ASC) VISIBLE,
  CONSTRAINT `fk_languages_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `RookiesCMS`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`CTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`CTA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link_text` VARCHAR(50) NOT NULL,
  `languages_id` INT NOT NULL,
  `value` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Navigation_languages1_idx` (`languages_id` ASC) VISIBLE,
  CONSTRAINT `fk_Navigation_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`navigation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`navigation` (
  `id` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `languages_id` INT NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `languages_id`),
  INDEX `fk_navbar_languages1_idx` (`languages_id` ASC) VISIBLE,
  CONSTRAINT `fk_navbar_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`Home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`Home` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  `CTA_text` VARCHAR(45) NOT NULL,
  `languages_id` INT NOT NULL,
  `navbar_id` INT NOT NULL,
  `images_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`, `navbar_id`, `images_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_module1E_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_Accueil_navbar1_idx` (`navbar_id` ASC) VISIBLE,
  INDEX `fk_Accueil_images1_idx` (`images_id` ASC) VISIBLE,
  CONSTRAINT `fk_module1E_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accueil_navbar1`
    FOREIGN KEY (`navbar_id`)
    REFERENCES `RookiesCMS`.`navigation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accueil_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `RookiesCMS`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`Carroussel_logo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`Carroussel_logo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `navbar_id` INT NOT NULL,
  `languages_id` INT NOT NULL,
  `images_id` INT NOT NULL,
  PRIMARY KEY (`id`, `navbar_id`, `languages_id`, `images_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Carroussel_logo_navbar1_idx` (`navbar_id` ASC) VISIBLE,
  INDEX `fk_Carroussel_logo_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_Carroussel_logo_images1_idx` (`images_id` ASC) VISIBLE,
  CONSTRAINT `fk_Carroussel_logo_navbar1`
    FOREIGN KEY (`navbar_id`)
    REFERENCES `RookiesCMS`.`navigation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carroussel_logo_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carroussel_logo_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `RookiesCMS`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`advantages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`advantages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `sub_title` VARCHAR(100) NOT NULL,
  `languages_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id1`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_module1S_languages2_idx` (`languages_id1` ASC) VISIBLE,
  CONSTRAINT `fk_module1S_languages2`
    FOREIGN KEY (`languages_id1`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`Process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`Process` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `sub_title` VARCHAR(100) NOT NULL,
  `text` VARCHAR(512) NOT NULL,
  `languages_id` INT NOT NULL,
  `images_id` INT NOT NULL,
  `navbar_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`, `images_id`, `navbar_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_module5E_languages2_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_Process_images1_idx` (`images_id` ASC) VISIBLE,
  INDEX `fk_Process_navbar1_idx` (`navbar_id` ASC) VISIBLE,
  CONSTRAINT `fk_module5E_languages2`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Process_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `RookiesCMS`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Process_navbar1`
    FOREIGN KEY (`navbar_id`)
    REFERENCES `RookiesCMS`.`navigation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`Process_element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`Process_element` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `text` VARCHAR(512) NOT NULL,
  `Process_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Process_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Process_element_Process1_idx` (`Process_id` ASC) VISIBLE,
  CONSTRAINT `fk_Process_element_Process1`
    FOREIGN KEY (`Process_id`)
    REFERENCES `RookiesCMS`.`Process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`carroussel_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`carroussel_review` (
  `id` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `sub_title` VARCHAR(100) NOT NULL,
  `languages_id` INT NOT NULL,
  `navbar_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`, `navbar_id`),
  INDEX `fk_module7E_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_carroussel_avis_navbar1_idx` (`navbar_id` ASC) VISIBLE,
  CONSTRAINT `fk_module7E_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carroussel_avis_navbar1`
    FOREIGN KEY (`navbar_id`)
    REFERENCES `RookiesCMS`.`navigation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`carroussel_review_element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`carroussel_review_element` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NOT NULL,
  `post` VARCHAR(45) NOT NULL,
  `testimonial` LONGTEXT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `carroussel_avis_id` INT NOT NULL,
  `images_id` INT NOT NULL,
  PRIMARY KEY (`id`, `carroussel_avis_id`, `images_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_carroussel_avis__element_carroussel_avis1_idx` (`carroussel_avis_id` ASC) VISIBLE,
  INDEX `fk_carroussel_avis__element_images1_idx` (`images_id` ASC) VISIBLE,
  CONSTRAINT `fk_carroussel_avis__element_carroussel_avis1`
    FOREIGN KEY (`carroussel_avis_id`)
    REFERENCES `RookiesCMS`.`carroussel_review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carroussel_avis__element_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `RookiesCMS`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`QA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`QA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tilte` VARCHAR(255) NOT NULL,
  `sub_title` VARCHAR(255) NOT NULL,
  `languages_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_module9E_languages1_idx` (`languages_id` ASC) VISIBLE,
  CONSTRAINT `fk_module9E_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`QA_element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`QA_element` (
  `id` INT NOT NULL,
  `question` LONGTEXT NOT NULL,
  `answer` LONGTEXT NOT NULL,
  `FAQ_id` INT NOT NULL,
  PRIMARY KEY (`id`, `FAQ_id`),
  INDEX `fk_FAQ_element_FAQ1_idx` (`FAQ_id` ASC) VISIBLE,
  CONSTRAINT `fk_FAQ_element_FAQ1`
    FOREIGN KEY (`FAQ_id`)
    REFERENCES `RookiesCMS`.`QA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`advantages_element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`advantages_element` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `avantages_id` INT NOT NULL,
  PRIMARY KEY (`id`, `avantages_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_avantages_element_avantages1_idx` (`avantages_id` ASC) VISIBLE,
  CONSTRAINT `fk_avantages_element_avantages1`
    FOREIGN KEY (`avantages_id`)
    REFERENCES `RookiesCMS`.`advantages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`presentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`presentation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `sub_title` VARCHAR(255) NOT NULL,
  `text1` LONGTEXT NOT NULL,
  `text2` LONGTEXT NOT NULL,
  `text3` LONGTEXT NOT NULL,
  `languages_id` INT NOT NULL,
  `images_id` INT NOT NULL,
  `CTA_label` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `images_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_presentation_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_presentation_images1_idx` (`images_id` ASC) VISIBLE,
  UNIQUE INDEX `languages_id_UNIQUE` (`languages_id` ASC) VISIBLE,
  CONSTRAINT `fk_presentation_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presentation_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `RookiesCMS`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`presentation_advantages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`presentation_advantages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `sous_titre` VARCHAR(255) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `languages_id` INT NOT NULL,
  `CTA_id` INT NOT NULL,
  `CTA_phone` VARCHAR(45) NOT NULL,
  `CTA_label` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `languages_id`, `CTA_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_presentation_avantages_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_presentation_avantages_CTA1_idx` (`CTA_id` ASC) VISIBLE,
  CONSTRAINT `fk_presentation_avantages_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presentation_avantages_CTA1`
    FOREIGN KEY (`CTA_id`)
    REFERENCES `RookiesCMS`.`CTA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`presentation_advantages_element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`presentation_advantages_element` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `summary` VARCHAR(255) NOT NULL,
  `details` LONGTEXT NOT NULL,
  `presentation_avantages_id` INT NOT NULL,
  PRIMARY KEY (`id`, `presentation_avantages_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_presentation_avantages_element_presentation_avantages1_idx` (`presentation_avantages_id` ASC) VISIBLE,
  CONSTRAINT `fk_presentation_avantages_element_presentation_avantages1`
    FOREIGN KEY (`presentation_avantages_id`)
    REFERENCES `RookiesCMS`.`presentation_advantages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`profit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`profit` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `sub_title` VARCHAR(255) NOT NULL,
  `languages_id` INT NOT NULL,
  `navbar_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`, `navbar_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_benefices_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_benefices_navbar1_idx` (`navbar_id` ASC) VISIBLE,
  CONSTRAINT `fk_benefices_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_benefices_navbar1`
    FOREIGN KEY (`navbar_id`)
    REFERENCES `RookiesCMS`.`navigation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`profit_elements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`profit_elements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `images_id` INT NOT NULL,
  `benefices_id` INT NOT NULL,
  PRIMARY KEY (`id`, `images_id`, `benefices_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_benefices_elements_images1_idx` (`images_id` ASC) VISIBLE,
  INDEX `fk_benefices_elements_benefices1_idx` (`benefices_id` ASC) VISIBLE,
  CONSTRAINT `fk_benefices_elements_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `RookiesCMS`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_benefices_elements_benefices1`
    FOREIGN KEY (`benefices_id`)
    REFERENCES `RookiesCMS`.`profit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`KPI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`KPI` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `sub_title` VARCHAR(255) NOT NULL,
  `languages_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_KPI_languages1_idx` (`languages_id` ASC) VISIBLE,
  CONSTRAINT `fk_KPI_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`KPI_element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`KPI_element` (
  `id` INT UNSIGNED NOT NULL,
  `number` FLOAT NOT NULL,
  `label` VARCHAR(70) NOT NULL,
  `KPI_id` INT NOT NULL,
  PRIMARY KEY (`id`, `KPI_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_KPI_element_KPI1_idx` (`KPI_id` ASC) VISIBLE,
  CONSTRAINT `fk_KPI_element_KPI1`
    FOREIGN KEY (`KPI_id`)
    REFERENCES `RookiesCMS`.`KPI` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`get_started`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`get_started` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `sub_title` VARCHAR(255) NOT NULL,
  `cta1_label` VARCHAR(100) NOT NULL,
  `cta2_label` VARCHAR(100) NOT NULL,
  `languages_id` INT NOT NULL,
  `CTA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`, `CTA_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_get_started_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_get_started_CTA1_idx` (`CTA_id` ASC) VISIBLE,
  CONSTRAINT `fk_get_started_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_get_started_CTA1`
    FOREIGN KEY (`CTA_id`)
    REFERENCES `RookiesCMS`.`CTA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`school_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`school_project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `languages_id` INT NOT NULL,
  `CTA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`, `CTA_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_projet_ecole_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_projet_ecole_CTA1_idx` (`CTA_id` ASC) VISIBLE,
  CONSTRAINT `fk_projet_ecole_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projet_ecole_CTA1`
    FOREIGN KEY (`CTA_id`)
    REFERENCES `RookiesCMS`.`CTA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`footer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`footer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(15) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `sub_title1` VARCHAR(255) NOT NULL,
  `sub_title2` VARCHAR(255) NOT NULL,
  `copyright` VARCHAR(255) NOT NULL,
  `terms` VARCHAR(100) NOT NULL,
  `policy` VARCHAR(100) NOT NULL,
  `newsletter` VARCHAR(100) NOT NULL,
  `languages_id` INT NOT NULL,
  `images_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`, `images_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_footer_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_footer_images1_idx` (`images_id` ASC) VISIBLE,
  CONSTRAINT `fk_footer_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_footer_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `RookiesCMS`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`contact_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`contact_form` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `CTA_label` VARCHAR(45) NOT NULL,
  `languages_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_formulaire_languages1_idx` (`languages_id` ASC) VISIBLE,
  UNIQUE INDEX `languages_id_UNIQUE` (`languages_id` ASC) VISIBLE,
  CONSTRAINT `fk_formulaire_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`newsletter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `selector` VARCHAR(45) NOT NULL,
  `languages_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_newsletter_languages1_idx` (`languages_id` ASC) VISIBLE,
  CONSTRAINT `fk_newsletter_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RookiesCMS`.`contact_form_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RookiesCMS`.`contact_form_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `languages_id` INT NOT NULL,
  `contact_form_id` INT NOT NULL,
  `newsletter_id` INT NOT NULL,
  PRIMARY KEY (`id`, `languages_id`, `contact_form_id`, `newsletter_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_formulaire_options_languages1_idx` (`languages_id` ASC) VISIBLE,
  INDEX `fk_contact_form_options_contact_form1_idx` (`contact_form_id` ASC) VISIBLE,
  INDEX `fk_contact_form_options_newsletter1_idx` (`newsletter_id` ASC) VISIBLE,
  CONSTRAINT `fk_formulaire_options_languages1`
    FOREIGN KEY (`languages_id`)
    REFERENCES `RookiesCMS`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_form_options_contact_form1`
    FOREIGN KEY (`contact_form_id`)
    REFERENCES `RookiesCMS`.`contact_form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_form_options_newsletter1`
    FOREIGN KEY (`newsletter_id`)
    REFERENCES `RookiesCMS`.`newsletter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
