-- MySQL Script generated by MySQL Workbench

-- Wed Jun 22 09:31:29 2022

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------

-- Schema RookiesCMS

-- -----------------------------------------------------

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET FOREIGN_KEY_CHECKS = 0;

SET
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------

-- Schema RookiesCMS

-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `RookiesCMS` DEFAULT CHARACTER SET utf8 ;

USE `RookiesCMS` ;

DROP TABLE IF EXISTS `RookiesCMS`.`languages` ;

DROP TABLE IF EXISTS `RookiesCMS`.`images` ;

DROP TABLE IF EXISTS `RookiesCMS`.`navigation` ;

DROP TABLE IF EXISTS `RookiesCMS`.`navigation_element` ;

DROP TABLE IF EXISTS `RookiesCMS`.`Home` ;

DROP TABLE IF EXISTS `RookiesCMS`.`Process` ;

DROP TABLE IF EXISTS `RookiesCMS`.`Process_element` ;

DROP TABLE IF EXISTS `RookiesCMS`.`carroussel_review` ;

DROP TABLE IF EXISTS `RookiesCMS`.`carroussel_review_element` ;

DROP TABLE IF EXISTS `RookiesCMS`.`QA` ;

DROP TABLE IF EXISTS `RookiesCMS`.`QA_element` ;

DROP TABLE IF EXISTS `RookiesCMS`.`presentation` ;

DROP TABLE IF EXISTS `RookiesCMS`.`presentation_advantages` ;

DROP TABLE IF EXISTS `RookiesCMS`.`presentation_advantages_element` ;

DROP TABLE IF EXISTS `RookiesCMS`.`profit` ;

DROP TABLE IF EXISTS `RookiesCMS`.`profit_elements` ;

DROP TABLE IF EXISTS `RookiesCMS`.`KPI` ;

DROP TABLE IF EXISTS `RookiesCMS`.`KPI_element` ;

DROP TABLE IF EXISTS `RookiesCMS`.`get_started` ;

DROP TABLE IF EXISTS `RookiesCMS`.`footer` ;

DROP TABLE IF EXISTS `RookiesCMS`.`contact_form` ;

DROP TABLE IF EXISTS `RookiesCMS`.`contact_form_and_newsletter_options`;

DROP TABLE IF EXISTS `RookiesCMS`.`newsletter_storage` ;

DROP TABLE IF EXISTS `RookiesCMS`.`quote` ;

DROP TABLE IF EXISTS `RookiesCMS`.`study_case_home` ;

DROP TABLE IF EXISTS `RookiesCMS`.`study_case_topics` ;

DROP TABLE IF EXISTS `RookiesCMS`.`project` ;

DROP TABLE IF EXISTS `RookiesCMS`.`project_menber` ;

DROP TABLE IF EXISTS `RookiesCMS`.`newsletter_component` ;

DROP TABLE IF EXISTS `RookiesCMS`.`cta_case_study` ;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`languages`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`languages` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `languages` VARCHAR(2) NOT NULL,
    `status` TINYINT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`images`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`images` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `image_link` LONGTEXT NOT NULL,
    `image_alt` VARCHAR(100) NOT NULL,
    `status` TINYINT NOT NULL,
    `url` VARCHAR(255) NULL,
    `categorie` VARCHAR(100) NOT NULL,
    `languages_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`),
    UNIQUE INDEX `idimages_UNIQUE` (`id` ASC),
    INDEX `fk_images_languages1_idx` (`languages_id` ASC),
    CONSTRAINT `fk_images_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`navigation`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`navigation` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `languages_id` INT NOT NULL,
    `images_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`, `images_id`),
    UNIQUE INDEX `index_UNIQUE` (`id` ASC),
    INDEX `fk_navigation_languages1_idx` (`languages_id` ASC),
    INDEX `fk_navigation_images1_idx` (`images_id` ASC),
    CONSTRAINT `fk_navigation_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_navigation_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`navigation_element`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`navigation_element` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `label` VARCHAR(45) NOT NULL,
    `path` VARCHAR(255) NULL,
    `link?` TINYINT NOT NULL,
    `navigation_id` INT NOT NULL,
    PRIMARY KEY (`id`, `navigation_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_navigation_element_navigation1_idx` (`navigation_id` ASC),
    CONSTRAINT `fk_navigation_element_navigation1` FOREIGN KEY (`navigation_id`) REFERENCES `RookiesCMS`.`navigation` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`Home`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`Home` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `title_green_part` VARCHAR(45) NOT NULL,
    `text` VARCHAR(255) NOT NULL,
    `CTA_label` VARCHAR(45) NOT NULL,
    `languages_id` INT NOT NULL,
    `navbar_id` INT NOT NULL,
    `images_id` INT NOT NULL,
    `background_images_id` INT NOT NULL,
    PRIMARY KEY (
        `id`,
        `languages_id`,
        `navbar_id`,
        `images_id`,
        `background_images_id`
    ),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_module1E_languages1_idx` (`languages_id` ASC),
    INDEX `fk_Accueil_navbar1_idx` (`navbar_id` ASC),
    INDEX `fk_Accueil_images1_idx` (`images_id` ASC),
    INDEX `fk_Home_images1_idx` (`background_images_id` ASC),
    CONSTRAINT `fk_module1E_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Accueil_navbar1` FOREIGN KEY (`navbar_id`) REFERENCES `RookiesCMS`.`navigation_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Accueil_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Home_images1` FOREIGN KEY (`background_images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`Process`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`Process` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `sub_title` VARCHAR(100) NOT NULL,
    `text` LONGTEXT NOT NULL,
    `languages_id` INT NOT NULL,
    `images_id` INT NOT NULL,
    `navbar_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`, `images_id`, `navbar_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_module5E_languages2_idx` (`languages_id` ASC),
    INDEX `fk_Process_images1_idx` (`images_id` ASC),
    INDEX `fk_Process_navbar1_idx` (`navbar_id` ASC),
    CONSTRAINT `fk_module5E_languages2` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Process_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_Process_navbar1` FOREIGN KEY (`navbar_id`) REFERENCES `RookiesCMS`.`navigation_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`Process_element`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`Process_element` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `text` LONGTEXT NOT NULL,
    `Process_id` INT NOT NULL,
    PRIMARY KEY (`id`, `Process_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_Process_element_Process1_idx` (`Process_id` ASC),
    CONSTRAINT `fk_Process_element_Process1` FOREIGN KEY (`Process_id`) REFERENCES `RookiesCMS`.`Process` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`carroussel_review`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`carroussel_review` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `sub_title` VARCHAR(100) NOT NULL,
    `languages_id` INT NOT NULL,
    `navbar_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`, `navbar_id`),
    INDEX `fk_module7E_languages1_idx` (`languages_id` ASC),
    INDEX `fk_carroussel_avis_navbar1_idx` (`navbar_id` ASC),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    CONSTRAINT `fk_module7E_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_carroussel_avis_navbar1` FOREIGN KEY (`navbar_id`) REFERENCES `RookiesCMS`.`navigation_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`carroussel_review_element`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`carroussel_review_element` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `fullname` VARCHAR(45) NOT NULL,
    `post` VARCHAR(45) NOT NULL,
    `testimonial` LONGTEXT NOT NULL,
    `type` VARCHAR(45) NOT NULL,
    `carroussel_avis_id` INT NOT NULL,
    `images_id` INT NOT NULL,
    `images_logo_id` INT NOT NULL,
    PRIMARY KEY (
        `id`,
        `carroussel_avis_id`,
        `images_id`,
        `images_logo_id`
    ),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_carroussel_avis__element_carroussel_avis1_idx` (`carroussel_avis_id` ASC),
    INDEX `fk_carroussel_avis__element_images1_idx` (`images_id` ASC),
    INDEX `fk_carroussel_review_element_images1_idx` (`images_logo_id` ASC),
    CONSTRAINT `fk_carroussel_avis__element_carroussel_avis1` FOREIGN KEY (`carroussel_avis_id`) REFERENCES `RookiesCMS`.`carroussel_review` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_carroussel_avis__element_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_carroussel_review_element_images1` FOREIGN KEY (`images_logo_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`QA`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`QA` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `sub_title` VARCHAR(255) NOT NULL,
    `languages_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_module9E_languages1_idx` (`languages_id` ASC),
    CONSTRAINT `fk_module9E_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`QA_element`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`QA_element` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `question` LONGTEXT NOT NULL,
    `answer` LONGTEXT NOT NULL,
    `FAQ_id` INT NOT NULL,
    PRIMARY KEY (`id`, `FAQ_id`),
    INDEX `fk_FAQ_element_FAQ1_idx` (`FAQ_id` ASC),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    CONSTRAINT `fk_FAQ_element_FAQ1` FOREIGN KEY (`FAQ_id`) REFERENCES `RookiesCMS`.`QA` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`presentation`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`presentation` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `sub_title` VARCHAR(255) NOT NULL,
    `text1` LONGTEXT NOT NULL,
    `text2` LONGTEXT NOT NULL,
    `text3` LONGTEXT NOT NULL,
    `languages_id` INT NOT NULL,
    `images_id` INT NOT NULL,
    `CTA_label` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`, `images_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_presentation_languages1_idx` (`languages_id` ASC),
    INDEX `fk_presentation_images1_idx` (`images_id` ASC),
    UNIQUE INDEX `languages_id_UNIQUE` (`languages_id` ASC),
    CONSTRAINT `fk_presentation_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_presentation_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`presentation_advantages`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`presentation_advantages` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `sub_title` VARCHAR(255) NOT NULL,
    `text` LONGTEXT NOT NULL,
    `languages_id` INT NOT NULL,
    `CTA_phone` VARCHAR(45) NOT NULL,
    `CTA_label` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`, `languages_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_presentation_avantages_languages1_idx` (`languages_id` ASC),
    CONSTRAINT `fk_presentation_avantages_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`presentation_advantages_element`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`presentation_advantages_element` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `summary` VARCHAR(255) NOT NULL,
    `details` LONGTEXT NOT NULL,
    `presentation_avantages_id` INT NOT NULL,
    PRIMARY KEY (`id`, `presentation_avantages_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_presentation_avantages_element_presentation_avantages1_idx` (`presentation_avantages_id` ASC),
    CONSTRAINT `fk_presentation_avantages_element_presentation_avantages1` FOREIGN KEY (`presentation_avantages_id`) REFERENCES `RookiesCMS`.`presentation_advantages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`profit`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`profit` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `sub_title` VARCHAR(255) NOT NULL,
    `languages_id` INT NOT NULL,
    `navigation_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`, `navigation_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_benefices_languages1_idx` (`languages_id` ASC),
    INDEX `fk_benefices_navbar1_idx` (`navigation_id` ASC),
    CONSTRAINT `fk_benefices_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_benefices_navbar1` FOREIGN KEY (`navigation_id`) REFERENCES `RookiesCMS`.`navigation_element` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`profit_elements`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`profit_elements` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `text` LONGTEXT NOT NULL,
    `profit_id` INT NOT NULL,
    PRIMARY KEY (`id`, `profit_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_benefices_elements_benefices1_idx` (`profit_id` ASC),
    CONSTRAINT `fk_benefices_elements_benefices1` FOREIGN KEY (`profit_id`) REFERENCES `RookiesCMS`.`profit` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`KPI`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`KPI` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `sub_title` VARCHAR(255) NOT NULL,
    `languages_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_KPI_languages1_idx` (`languages_id` ASC),
    CONSTRAINT `fk_KPI_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`KPI_element`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`KPI_element` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `number` FLOAT NOT NULL,
    `label` VARCHAR(70) NOT NULL,
    `KPI_id` INT NOT NULL,
    PRIMARY KEY (`id`, `KPI_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_KPI_element_KPI1_idx` (`KPI_id` ASC),
    CONSTRAINT `fk_KPI_element_KPI1` FOREIGN KEY (`KPI_id`) REFERENCES `RookiesCMS`.`KPI` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`get_started`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`get_started` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `cta1_label` VARCHAR(100) NOT NULL,
    `cta2_label` VARCHAR(100) NOT NULL,
    `languages_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_get_started_languages1_idx` (`languages_id` ASC),
    CONSTRAINT `fk_get_started_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`footer`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`footer` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `phone_number` VARCHAR(15) NOT NULL,
    `mail` VARCHAR(255) NOT NULL,
    `sub_title1` VARCHAR(255) NOT NULL,
    `sub_title2` VARCHAR(255) NOT NULL,
    `copyright` VARCHAR(255) NOT NULL,
    `terms` VARCHAR(100) NOT NULL,
    `policy` VARCHAR(100) NOT NULL,
    `newsletter` VARCHAR(100) NOT NULL,
    `languages_id` INT NOT NULL,
    `images_logo1_id` INT NOT NULL,
    `images_logo2_id` INT NOT NULL,
    `rookies_logo` INT NOT NULL,
    `instagram_logo` INT NOT NULL,
    `linkedin_logo` INT NOT NULL,
    PRIMARY KEY (
        `id`,
        `languages_id`,
        `images_logo1_id`,
        `images_logo2_id`,
        `rookies_logo`,
        `instagram_logo`,
        `linkedin_logo`
    ),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_footer_languages1_idx` (`languages_id` ASC),
    INDEX `fk_footer_images1_idx` (`images_logo1_id` ASC),
    INDEX `fk_footer_images2_idx` (`images_logo2_id` ASC),
    INDEX `fk_footer_images3_idx` (`rookies_logo` ASC),
    INDEX `fk_footer_images4_idx` (`instagram_logo` ASC),
    INDEX `fk_footer_images5_idx` (`linkedin_logo` ASC),
    CONSTRAINT `fk_footer_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_footer_images1` FOREIGN KEY (`images_logo1_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_footer_images2` FOREIGN KEY (`images_logo2_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_footer_images3` FOREIGN KEY (`rookies_logo`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_footer_images4` FOREIGN KEY (`instagram_logo`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_footer_images5` FOREIGN KEY (`linkedin_logo`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`contact_form`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`contact_form` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `fullname` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    `CTA_label` VARCHAR(45) NOT NULL,
    `languages_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_formulaire_languages1_idx` (`languages_id` ASC),
    UNIQUE INDEX `languages_id_UNIQUE` (`languages_id` ASC),
    CONSTRAINT `fk_formulaire_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`contact_form_and_newsletter_options`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`contact_form_and_newsletter_options` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `text` VARCHAR(45) NOT NULL,
    `value` VARCHAR(45) NOT NULL,
    `languages_id` INT NOT NULL,
    `contact_form_id` INT NOT NULL,
    `footer_id` INT NOT NULL,
    PRIMARY KEY (
        `id`,
        `languages_id`,
        `contact_form_id`,
        `footer_id`
    ),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_formulaire_options_languages1_idx` (`languages_id` ASC),
    INDEX `fk_contact_form_options_contact_form1_idx` (`contact_form_id` ASC),
    INDEX `fk_contact_form_and_newsletter_options_footer1_idx` (`footer_id` ASC),
    CONSTRAINT `fk_formulaire_options_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_contact_form_options_contact_form1` FOREIGN KEY (`contact_form_id`) REFERENCES `RookiesCMS`.`contact_form` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_contact_form_and_newsletter_options_footer1` FOREIGN KEY (`footer_id`) REFERENCES `RookiesCMS`.`footer` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`newsletter_storage`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`newsletter_storage` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(255) NOT NULL,
    `languages_id` INT NOT NULL,
    `contact_form_and_newsletter_options_id` INT NOT NULL,
    PRIMARY KEY (
        `id`,
        `languages_id`,
        `contact_form_and_newsletter_options_id`
    ),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_newsletter_languages1_idx` (`languages_id` ASC),
    INDEX `fk_newsletter_storage_contact_form_and_newsletter_options1_idx` (`contact_form_and_newsletter_options_id` ASC),
    CONSTRAINT `fk_newsletter_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_newsletter_storage_contact_form_and_newsletter_options1` FOREIGN KEY (`contact_form_and_newsletter_options_id`) REFERENCES `RookiesCMS`.`contact_form_and_newsletter_options` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`quote`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`quote` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `quote` LONGTEXT NOT NULL,
    `quote_green_part` VARCHAR(100) NOT NULL,
    `author` VARCHAR(100) NOT NULL,
    `languages_id` INT NOT NULL,
    `images_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`, `images_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_quote_languages1_idx` (`languages_id` ASC),
    INDEX `fk_quote_images1_idx` (`images_id` ASC),
    CONSTRAINT `fk_quote_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_quote_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`study_case_home`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`study_case_home` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `title_green_part` VARCHAR(100) NOT NULL,
    `text` VARCHAR(255) NOT NULL,
    `cta_label` VARCHAR(100) NOT NULL,
    `label_topics` VARCHAR(100) NOT NULL,
    `topic` VARCHAR(45) NOT NULL,
    `languages_id` INT NOT NULL,
    `images_id` INT NOT NULL,
    `topic_img_id` INT NOT NULL,
    PRIMARY KEY (
        `id`,
        `languages_id`,
        `images_id`,
        `topic_img_id`
    ),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_study_case_home_languages1_idx` (`languages_id` ASC),
    INDEX `fk_study_case_home_images1_idx` (`images_id` ASC),
    INDEX `fk_study_case_home_images2_idx` (`topic_img_id` ASC),
    CONSTRAINT `fk_study_case_home_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_study_case_home_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_study_case_home_images2` FOREIGN KEY (`topic_img_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`study_case_topics`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`study_case_topics` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `sub_title` VARCHAR(100) NOT NULL,
    `images_id` INT NOT NULL,
    `study_case_home_id` INT NOT NULL,
    PRIMARY KEY (`id`, `images_id`, `study_case_home_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_study_case_topics_images1_idx` (`images_id` ASC),
    INDEX `fk_study_case_topics_study_case_home1_idx` (`study_case_home_id` ASC),
    CONSTRAINT `fk_study_case_topics_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_study_case_topics_study_case_home1` FOREIGN KEY (`study_case_home_id`) REFERENCES `RookiesCMS`.`study_case_home` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`project`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`project` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `sub_title` VARCHAR(100) NOT NULL,
    `description` VARCHAR(100) NOT NULL,
    `time_week` VARCHAR(100) NOT NULL,
    `time_hour` VARCHAR(100) NOT NULL,
    `text` LONGTEXT NOT NULL,
    `signature` VARCHAR(100) NOT NULL,
    `amount` FLOAT NOT NULL,
    `status` TINYINT NOT NULL,
    `languages_id` INT NOT NULL,
    `images_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`, `images_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_project_languages1_idx` (`languages_id` ASC),
    INDEX `fk_project_images1_idx` (`images_id` ASC),
    CONSTRAINT `fk_project_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_project_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`project_menber`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`project_menber` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `project_id` INT NOT NULL,
    `images_id` INT NOT NULL,
    PRIMARY KEY (`id`, `project_id`, `images_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_project_menber_project1_idx` (`project_id` ASC),
    INDEX `fk_project_menber_images1_idx` (`images_id` ASC),
    CONSTRAINT `fk_project_menber_project1` FOREIGN KEY (`project_id`) REFERENCES `RookiesCMS`.`project` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_project_menber_images1` FOREIGN KEY (`images_id`) REFERENCES `RookiesCMS`.`images` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`newsletter_component`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`newsletter_component` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NOT NULL,
    `text` LONGTEXT NOT NULL,
    `cta_label` VARCHAR(45) NOT NULL,
    `languages_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_newsletter_component_languages1_idx` (`languages_id` ASC),
    CONSTRAINT `fk_newsletter_component_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------

-- Table `RookiesCMS`.`cta_case_study`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `RookiesCMS`.`cta_case_study` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `text` LONGTEXT NOT NULL,
    `cta_label` VARCHAR(100) NOT NULL,
    `languages_id` INT NOT NULL,
    PRIMARY KEY (`id`, `languages_id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC),
    INDEX `fk_cta_case_study_languages1_idx` (`languages_id` ASC),
    CONSTRAINT `fk_cta_case_study_languages1` FOREIGN KEY (`languages_id`) REFERENCES `RookiesCMS`.`languages` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

insert into
    `RookiesCMS`.`languages` (languages, status)
VALUES
    ("EN", 1),
    ("FR", 0);

insert into
    `RookiesCMS`.`images`(
        image_link,
        image_alt,
        status,
        url,
        categorie,
        languages_id
    )
VALUES
    (
        "https://i.ibb.co/HDd5xBF/you.png",
        "Youmeal",
        0,
        "https://youmeal.io/",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/gmC8GKc/home.png",
        "Homecore",
        0,
        "https://www.homecore.com/fr/",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/4SYjjrC/emma.png",
        "Emma",
        0,
        "https://www.tendances-emma.fr/",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/h7JB3Fj/keye.png",
        "Keyena",
        0,
        "https://keyena.com/",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/xfWCDZf/sowa.png",
        "Sowapi",
        0,
        "https://sowapi.ch/",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/n7Dnf0g/PPa.png",
        "PPA Business School",
        0,
        "https://www.ppa.fr/ecole-commerce-alternance.html",
        "logo",
        1
    ),
    (
        "https://www.em-normandie.com/themes/custom/emn/images/EM-Logo-2018-default.png",
        "Normandie Business School",
        0,
        "https://www.em-normandie.com/fr",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/K2zxYq4/stras.png",
        "EM Strasbourg",
        0,
        "https://www.em-strasbourg.com/fr",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/WfzKyg6/junia.png",
        "Junia",
        0,
        "https://www.junia.com/",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/YQwsp6d/wild.png",
        "Wild Code School",
        0,
        "https://www.wildcodeschool.com/",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/Kw3NZyh/hetic.png",
        "Hetic",
        0,
        "https://www.hetic.net/",
        "logo",
        1
    ),
    (
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Saxion_University_of_Applied_Sciences_logo.svg/1200px-Saxion_University_of_Applied_Sciences_logo.svg.png",
        "Saxion",
        0,
        "https://www.saxion.edu/",
        "logo",
        1
    ),
    (
        "https://fontys.edu/static/fontysrdpresentation/images/defaultsocialmediaimage.jpeg",
        "Fontys",
        0,
        "https://fontys.edu/Home.htm",
        "logo",
        1
    ),
    (
        "https://www.efficom.fr/images/2019/10/logo-EFFICOM-V2okblanc.png",
        "Efficom",
        0,
        "https://www.efficom.fr/",
        "logo",
        1
    ),
    (
        "https://pbs.twimg.com/profile_images/887211284369944577/xqN4uf35_400x400.jpg",
        "FHNW",
        0,
        "https://www.fhnw.ch/de",
        "logo",
        1
    ),
    (
        "https://tamba-labs.com/wp-content/uploads/2020/12/Logo_Homepage_Main.png",
        "Tamba Labs",
        0,
        "https://tamba-labs.com/",
        "logo",
        1
    ),
    (
        "https://www.iscom.fr/themes/custom/iscom/images/logo.png",
        "Iscom",
        0,
        "https://www.iscom.fr/",
        "logo",
        1
    ),
    (
        "https://mon-magasin-en-ville.fr/wp-content/uploads/2021/10/logo-MMEV-600px-96.png",
        "Mon Magasin en Ville",
        0,
        "https://mon-magasin-en-ville.fr/",
        "logo",
        1
    ),
    (
        "https://media-exp1.licdn.com/dms/image/C4D0BAQEnuytb7N4eHA/company-logo_200_200/0/1637244902902?e=1662595200&v=beta&t=1sUN3rirGsRS8zjy2s91V-P3e1vLbJRLnG6tQSY6ScU",
        "La Biscuiterie Handi-Gaspi",
        0,
        "https://www.linkedin.com/company/la-biscuiterie-handi-gaspi/?originalSubdomain=fr",
        "logo",
        1
    ),
    (
        "https://www.unilasalle.fr/themes/custom/unilasalle/logo.svg",
        "UniLaSalle",
        0,
        "https://www.unilasalle.fr/",
        "logo",
        1
    ),
    (
        "https://www.iim.fr/ecole-web/wp-content/uploads/2020/09/logo-iim-paris.png",
        "IIM",
        0,
        "https://www.iim.fr/",
        "logo",
        1
    ),
    (
        "https://www.cpe.fr/wp-content/themes/acti-main/img/logo-cpe-bleu.svg",
        "CPE Lyon",
        0,
        "https://www.cpe.fr/",
        "logo",
        1
    ),
    (
        "https://static.wixstatic.com/media/6351e4_54c8eac235d649099f4a167ddaebf4de~mv2.png/v1/fill/w_357,h_165,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Gamechangers%20logo.png",
        "GameChangers NFT",
        0,
        "https://www.gamechangenft.com/",
        "logo",
        1
    ),
    (
        "https://i.ibb.co/HNmWxvB/Rookies-Logo.png",
        "Rookies",
        0,
        "https://rookies-cms.remote-fr-4.wilders.dev/page1/1",
        "RookiesLogo",
        1
    ),
    (
        "https://i.ibb.co/BVVGRFR/image3E.png",
        "Win Win",
        0,
        "",
        "ImgPresentation",
        1
    ),
    (
        "https://i.ibb.co/RzT7xyK/imgm1.png",
        "Students",
        0,
        "",
        "ImgHome",
        1
    ),
    (
        "https://i.ibb.co/yV7CZsd/module5E.png",
        "Talents",
        0,
        "",
        "ImgProcess ",
        1
    ),
    (
        "https://i.ibb.co/5TTHJjL/bravetype1.png",
        "Homecore Men",
        0,
        "",
        "ImgCarouselReviewCompany",
        1
    ),
    (
        "https://i.ibb.co/N9g70zK/bravetype2.png",
        "You Meal Men",
        0,
        "",
        "ImgCarouselReviewCompany",
        1
    ),
    (
        "https://i.ibb.co/RPQxjQk/bravefille1.png",
        "Keyena Girl",
        0,
        "",
        "ImgCarouselReviewCompany",
        1
    ),
    (
        "https://i.ibb.co/WkhbPwG/bravetype3.png",
        "PPA Men",
        0,
        "",
        "ImgCarouselReviewSchool",
        1
    ),
    (
        "https://ibb.co/jJPp98Z",
        "logo pépite",
        0,
        "https://pepite-provence.pepitizy.fr/fr",
        "logofooter",
        1
    ),
    (
        "https://ibb.co/vxNP6qq",
        "logo la french tech",
        0,
        "https://lafrenchtech.com/fr/",
        "logofooter",
        1
    ),
    (
        "https://i.ibb.co/W2mNBmr/3.png",
        "3 petits points encerclés",
        0,
        "",
        "ProjectsExamples",
        1
    ),
    (
        "https://i.ibb.co/m5vBkMT/classroom.png",
        "Classroom",
        0,
        "",
        "ProjectsExamples",
        1
    ),
    (
        "https://ibb.co/mNYLY2R",
        "Home background",
        0,
        "",
        "Background",
        1
    ),
    (
        "https://i.ibb.co/jWNWCGV/caf-livre.png",
        "Book & cofee",
        0,
        "",
        "Quote Img",
        1
    ),
    (
        "https://i.ibb.co/t30CjGZ/grec.png",
        "Greek Column",
        0,
        "",
        "Quote Img",
        1
    ),
    (
        "https://img-4.linternaute.com/BORGWOduhCqgz_bxlnxXpU2PEL4=/fit-in/x630/smart/filters:fill(1D1D1B)/685fdd5cfcf444e08d3ff22cde5d1581/ccmcms-linternaute/2377659.jpg",
        "Beautiful cliffs",
        0,
        "",
        "Quote Img",
        1
    ),
    (
        "https://www.okvoyage.com/wp-content/uploads/2021/02/paysages-norvege-810x538.jpeg",
        "Beautiful village",
        0,
        "",
        "Quote Img",
        1
    ),
    (
        "https://www.okvoyage.com/wp-content/uploads/2021/08/paysages-de-france-scaled.jpg",
        "Beautiful waterfall",
        0,
        "",
        "Quote Img",
        1
    ),
    (
        "https://resize-elle.ladmedia.fr/rcrop/638,,forcex/img/var/plain_site/storage/images/loisirs/evasion/paysage-ensoleille/90705820-1-fre-FR/Ces-paysages-ensoleilles-boosteront-votre-moral-toute-l-annee.jpg",
        "Beautiful beach",
        0,
        "",
        "Quote Img",
        1
    ),
    (
        "https://static.wixstatic.com/media/108ff4_00a3ac6d7c5a4f5d826f8fb99d4fc35a~mv2.jpg/v1/fill/w_640,h_400,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/108ff4_00a3ac6d7c5a4f5d826f8fb99d4fc35a~mv2.jpg",
        "Beautiful boat",
        0,
        "",
        "Quote Img",
        1
    ),
    (
        "https://www.okvoyage.com/wp-content/uploads/2021/08/le-mont-saint-michel-parmi-les-plus-beaux-paysages-de-france-1024x683.jpg",
        "Beautiful Castle",
        0,
        "",
        "Quote Img",
        1
    ),
    (
        "https://img.freepik.com/photos-gratuite/paysage-paisible-paisible-campagne-propre-flux_1417-1106.jpg?w=2000",
        "Beautiful bay",
        0,
        "",
        "Quote Img",
        1
    ),
    (
        "https://images.zeald.com/site/detourau/images/Australie/Australie%20info%20et%20articles/5paysages/Iles.jpg",
        "Beautiful island",
        0,
        "",
        "Quote Img",
        1
    ),(
        "https://ibb.co/9vVzskR",
        "HOMECORE x EM Normandie",
        0,
        "",
        "Project menber",
        1
    ),(
        "https://ibb.co/BfRPFDg",
        "KEYENA x PPA Business School",
        0,
        "",
        "Project menber",
        1
    ),(
        "https://ibb.co/nD8CphK",
        "project menber",
        0,
        "",
        "Project menber",
        1
    ),(
        "https://ibb.co/bQ1s3LV",
        "project menber 2",
        0,
        "",
        "Project menber",
        1
    ),(
        "https://ibb.co/8zrdzPf",
        "project menber 3",
        0,
        "",
        "Project menber",
        1
    ),(
        "https://ibb.co/gymsbtq",
        "topic logo",
        0,
        "",
        "Topic Main Logo",
        1
    ),(
        "https://ibb.co/D8LjSvs",
        "Topic BackGround",
        0,
        "",
        "Topic BackGround",
        1
    ),(
        "https://ibb.co/JcL4kwf",
        "Topic Logo",
        0,
        "",
        "Topic Logo",
        1
    ),(
        "https://ibb.co/WKMjnjq",
        "Topic Logo",
        0,
        "",
        "Topic Logo",
        1
    ),(
        "https://ibb.co/qJzZYjY",
        "Topic Logo",
        0,
        "",
        "Topic Logo",
        1
    ),(
        "https://ibb.co/gSMh0dT",
        "Topic Logo",
        0,
        "",
        "Topic Logo",
        1
    ),(
        "https://ibb.co/YbrPvqG",
        "Topic Logo",
        0,
        "",
        "Topic Logo",
        1
    ),(
        "https://ibb.co/jbPh8pN",
        "instagram Logo",
        0,
        "",
        "RS Logo",
        1
    ),(
        "https://ibb.co/crsxSVd",
        "Linkedin Logo",
        0,
        "https://www.linkedin.com/company/rookiesprojects/?originalSubdomain=fr",
        "RS Logo",
        1
    );

insert into
    `RookiesCMS`.`navigation`(languages_id, images_id)
VALUES
    (1, 24);

insert into
    `RookiesCMS`.`navigation_element` (label, path, navigation_id, `link?`)
VALUES
    ("Companies", "/", 1, 0),
    ("Universities", "/page2", 1, 0),
    ("Students", "/page3", 1, 0),
    ("About us", "/page4", 1, 0),
    ("Contact us", "", 1, 1);

insert into
    `RookiesCMS`.`QA` (title, sub_title, languages_id)
VALUES
    (
        "Do you have some questions ?",
        "Frequently asked questions",
        1
    );

insert into
    `RookiesCMS`.`QA_element`(question, answer, FAQ_id)
VALUES
    (
        "What is a Rookies project ?",
        "lorem ipsum dolor sit amet",
        1
    ),
    (
        "Why should my company launch a Rookie project ?",
        "upgrade to the Team Plan for unlimited guests. You can also review and remove inactive guests in Setting & Menbers.",
        1
    ),
    (
        "What kind of projects can be conducted ?",
        "lorem ipsum dolor sit amet",
        1
    ),
    (
        "What about data privacy and intellectual property ?",
        "lorem ipsum dolor sit amet",
        1
    ),
    (
        "How much time do i need to allocate to the project ?",
        "lorem ipsum dolor sit amet",
        1
    );

insert into
    `RookiesCMS`.`presentation_advantages` (
        title,
        sub_title,
        text,
        languages_id,
        CTA_phone,
        CTA_label
    )
VALUES
    (
        "Why launch a Rookies Project?",
        "A Better way to hire talents",
        "Engage with students on your company specific projects, so the can demonstrate their capabilities before they are hired full time.",
        1,
        "+33785680988",
        "Book a meeting"
    );

insert into
    `RookiesCMS`.`presentation_advantages_element` (summary, details, presentation_avantages_id)
VALUES
    (
        "A support for your team",
        "lorem ipsum dolor sit amet",
        1
    ),(
        "Boost your employer brand",
        "Today's students are tommortow's decision makers. When they engage with your company. You become an employer of choice. This collaboration will be with them for years to come.",
        1
    ),(
        "Go beyound CVs",
        "lorem ipsum dolor sit amet",
        1
    );

insert into
    `RookiesCMS`.`presentation` (
        title,
        sub_title,
        text1,
        text2,
        text3,
        languages_id,
        images_id,
        CTA_label
    )
VALUES
    (
        "What is a Rookies Project?",
        "A win-win collaboration",
        "Submit an assignement specific to your company, taken on by higher educaton students. The projects are carried out remotely or in person as part of the students' curriculum with the support of a qualified supervisor.",
        "Studenrs acquire resume worthy experience and connect with employers",
        "Compagnies get answers to their challenges and discover talents",
        1,
        25,
        "Get Started"
    );
insert into
    `RookiesCMS`.`profit` (title, sub_title, languages_id, navigation_id)
VALUES
    (
        "Benefits of working with us",
        "A turnkey solution",
        1,
        1
    );
insert into
    `RookiesCMS`.`profit_elements` (title, text, profit_id)
VALUES
    (
        "Easily design your projects",
        "Express tour nees and objectives in few clicks or talk with one of our experts and we take care of the rest.",
        1
    ),
    (
        "Access a large network",
        "More than 500 opportunities referenced in our project database in France and abroad.",
        1
    ),
    (
        "Simplified project management",
        "We take care of all administrative tasks ans provide with a platrform to manage your projects efficienly.",
        1
    ),
    (
        "Detailled Reports",
        "Lorem ipsum dolor sit amet, consectetur adpiscing elit. Mattis et sed nam sem tellus erat.",
        1
    );
insert into
    `RookiesCMS`.`KPI` (title, sub_title, languages_id)
VALUES
    (
        "Key Figures",
        "Our achievement depicted in numbers",
        1
    );
insert into
    `RookiesCMS`.`KPI_element` (number, label, KPI_id)
VALUES
    (50, "Projects", 1),
    (30, "clients", 1),
    (300, "Student participants", 1),
    (5, "Countries", 1);
insert into
    `RookiesCMS`.`get_started` (
        cta1_label,
        cta2_label,
        languages_id
    )
VALUES
    (
        "More questions?",
        "Start Now",
        1
    );
insert into
    `RookiesCMS`.`contact_form` (
        fullname,
        email,
        description,
        CTA_label,
        languages_id
    )
VALUES
    (
        "first name & Last name",
        "Email",
        "Message",
        "Submit",
        1
    );
insert into
    `RookiesCMS`.`Home` (
        title,
        title_green_part,
        text,
        CTA_label,
        languages_id,
        navbar_id,
        images_id,
        background_images_id
    )
VALUES
    (
        'Get more done, while connecting with ',
        "great talent",
        "Involve students in your projects and identify your future talents.",
        "Get started",
        1,
        1,
        26,
        36
    );
insert into
    `RookiesCMS`.`Process` (
        title,
        sub_title,
        text,
        languages_id,
        images_id,
        navbar_id
    )
VALUES
    (
        "How does it works ?",
        "Test talents while working on meaningful projects",
        "Easily build and manage your experiential hiring projects to support your team and identify your future workforce.",
        1,
        27,
        1
    );
insert into
    `RookiesCMS`.`Process_element` (title, text, Process_id)
VALUES
    (
        "Design",
        "indicate your goals, timeline, and candidate requirements.",
        1
    ),
    (
        "Select & Start",
        "Get proposals,select and launch your project.",
        1
    ),
    (
        "Manage",
        "Easiliy manage the progression of your project with our platform.",
        1
    ),
    (
        "Evaluate & integrate",
        "identify the top performers and integrate the best solutions.",
        1
    );
insert into
    `RookiesCMS`.`carroussel_review` (title, sub_title, languages_id, navbar_id)
VALUES
    (
        "Testimonials",
        "What our customers say about us",
        1,
        1
    );
insert into
    `RookiesCMS`.`carroussel_review_element` (
        fullname,
        post,
        testimonial,
        type,
        carroussel_avis_id,
        images_id,
        images_logo_id
    )
VALUES
    (
        "Alexandre Guarneri",
        "Founder @HOMECORE",
        "The audit conducted by the Tookies raised many essential questions for Homcore and several of their recommendations will be implemented on our website.",
        1,
        1,
        28,
        2
    ),
    (
        "Xavier Sourceau",
        "Chief revenue Officier @YOUMEAL",
        "The audit conducted by the Tookies raised many essential questions for Homcore and several of their recommendations will be implemented on our website.",
        1,
        1,
        29,
        1
    ),
    (
        "Carolie Gassama",
        "Founder & CEO @KEYENA",
        "The audit conducted by the Tookies raised many essential questions for Homcore and several of their recommendations will be implemented on our website.",
        1,
        1,
        30,
        4
    );
insert into
    `RookiesCMS`.`footer`(
        phone_number,
        mail,
        sub_title1,
        sub_title2,
        copyright,
        terms,
        policy,
        newsletter,
        languages_id,
        images_logo1_id,
        images_logo2_id,
        rookies_logo,
        instagram_logo,
        linkedin_logo
    )
VALUES
    (
        "+33(0)785680988",
        "contact@rookiesprojects.com",
        "Quick Links",
        "Join our newsletter",
        "© 2022 Rookies SAS. All rights reserved",
        "General Terms",
        "Privacy Policy",
        "Your Email",
        1,
        32,
        33,
        24,
        49,
        50
    );
insert into
    `RookiesCMS`.`contact_form_and_newsletter_options`(
        text,
        value,
        languages_id,
        contact_form_id,
        footer_id
    )
VALUES
    ("Company", "Company", 1, 1, 1),
    ("School", "School", 1, 1, 1);
INSERT INTO
    `RookiesCMS`.`quote`(
        quote,
        quote_green_part,
        author,
        languages_id,
        images_id
    )
VALUES
    (
        "Ce que nous devons aprrendre à faire, ",
        "nous l'apprendrons en le faisant.",
        "📜  Aristote",
        1,
        38
    ),(
        "The best way of learning about anything ",
        "is by doing.",
        "💬  Richard Branson",
        1,
        37
    );

INSERT INTO
    `RookiesCMS`.`newsletter_component`(
        title,
        text,
        cta_label,
        languages_id
    )
VALUES(
        "Subscribe to Our Newsletter",
        "We have hiking-related blog so we can share our thought and rutinity in our blog that updated weekly. We will not spam you, we promise.",
        "Subscribe",
        1
    );

INSERT INTO
    `RookiesCMS`.`cta_case_study`(
        text,
        cta_label,
        languages_id
    )
VALUES(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        "Check it Out",
        1
    );

INSERT INTO
    `RookiesCMS`.`project`(
        title,
        sub_title,
        description,
        time_week,
        time_hour,
        text,
        signature,
        amount,
        status,
        languages_id,
        images_id
    )
VALUES(
        "HOMECORE x EM Normandie",
        "Audit SEO & SEA",
        "M2 Marketing Digital - Parcours Grande Ecole",
        "8 semaines de projet",
        "400 heures de travail",
        "Wise busy past both park when an ye no. Nay likely her length sooner thrown sex lively income. The expense windows .",
        "- Mike Taylor, Web Designer",
        6,
        0,
        1,
        47
    ),(
        "KEYENA x PPA Business School",
        "Étude de marché",
        "3A de Bachelor Management du Sport ",
        "8 semaines de projet",
        "400 heures de travail",
        "Wise busy past both park when an ye no. Nay likely her length sooner thrown sex lively income. The expense windows .",
        "- Mike Taylor, Web Designer",
        6,
        1,
        1,
        48
    ),(
        "OBOX x ISE Junia",
        "Étude de faisabilité",
        "M2 Marketing Digital - Parcours Grande Ecole",
        "8 semaines de projet",
        "400 heures de travail",
        "Wise busy past both park when an ye no. Nay likely her length sooner thrown sex lively income. The expense windows .",
        "- Mike Taylor, Web Designer",
        6,
        0,
        1,
        47
    ),(
        "Mon Magasin en Ville x HETIC",
        "Conception UX/UI",
        "M2 Marketing Digital - Parcours Grande Ecole",
        "8 semaines de projet",
        "400 heures de travail",
        "Wise busy past both park when an ye no. Nay likely her length sooner thrown sex lively income. The expense windows .",
        "- Mike Taylor, Web Designer",
        6,
        1,
        1,
        47
    );

INSERT INTO
    `RookiesCMS`.`project_menber`(project_id, images_id)
VALUES(1, 49),(1, 50),(1, 51);

INSERT INTO
    `RookiesCMS`.`study_case_home`(
        title,
        title_green_part,
        text,
        cta_label,
        label_topics,
        topic,
        languages_id,
        images_id,
        topic_img_id
    )
VALUES
    (
        "No matter your challenge",
        "Rookies can handle it",
        "A talented team to help you in your journey on creating usefull and easy to use product",
        "Let's Talk",
        "Multiple Topics",
        "And More ...",
        1,
        53,
        52
    );
INSERT INTO
    `RookiesCMS`.`study_case_topics`(title, sub_title, images_id, study_case_home_id)
VALUES("Marketing", "Étude de marché", 56, 1),("Communication", "Mentor of Web Design", 57, 1),("Digital et Web", "Developpement", 58, 1),("Graphisme", "Mentor of UI/UX", 54, 1),("Ingénierie", "Mentor of UI/UX", 55, 1);